### ISSUE TITLE
epic: improve existing crafting recipes.

### ISSUE THREAD

**Issue by pollend** [Terasology/JoshariasSurvival#53]
tasks to complete: 
- [ ] door (https://github.com/Terasology/JoshariasSurvival/issues/54)
- [ ] chest (https://github.com/Terasology/JoshariasSurvival/issues/55)
- [ ] fence (https://github.com/Terasology/JoshariasSurvival/issues/56)
- [ ] Glass (https://github.com/Terasology/JoshariasSurvival/issues/57)
- [ ] Cobblestone (https://github.com/Terasology/JoshariasSurvival/issues/58)
- [ ] Plank Stairs (https://github.com/Terasology/JoshariasSurvival/issues/67)
